services:
  giropops-senhas:
    image: brunochiconato/giropops-senhas:1.0
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes:
      - strigus:/strigus

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - giropops
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  strigus:

networks:
  giropops:
    driver: bridge