services:
  giropops-senhas:
    image: brunochiconato/giropops-senhas:1.0
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes:
      - strigus:/strigus

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - giropops

volumes:
  strigus:

networks:
  giropops:
    driver: bridge