FROM golang:1.18 AS build
WORKDIR /app
COPY hello.go ./
RUN go mod init hello
RUN go build -o /app/hello

FROM alpine:3.15.9
COPY --from=build /app/hello /app/hello
ENV APP="hello_world"
ARG GIROPOPS="strigus"
RUN echo "ARG GIROPOPS = $GIROPOPS"
CMD ["/app/hello"]